name: Ubuntu Scraper Testing

on:
  push:
    branches: [ dev,release ]
  pull_request:
    branches: [ dev,release ]

permissions:
  contents: read

jobs:
  All-Checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup
      run: |
        pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Testing
      run: |
        pipenv run pytest testing
    - name: Lint
      run: |
        pipenv run pylint $(git ls-files '*.py')
    - name: Create Executable
      run: |
        pipenv run pyinstaller --name Lyzer-Scraper --add-data backup/:data/ lyzer_scraper.py
    - name: Security Check
      run: |
        pipenv check