name: Ubuntu Scraper Testing

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ dev,release ]

permissions:
  contents: read

jobs:
  All-Checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup
      run: |
        pip install --upgrade pip
        pip install pipenv
        pipenv install
        apt-get update &&
        wget "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" -P /tmp &&
        apt-get install -y "/tmp/google-chrome-stable_current_amd64.deb" -f
    - name: Testing
      run: |
        pipenv run pytest -v testing
    - name: Lint
      run: |
        pipenv run pylint $(git ls-files '*.py')
    - name: Security Check
      run: |
        pipenv check