name: Windows Scraper Testing

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

permissions:
  contents: read

jobs:
  All-Checks:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup
      run: |
        pip install --upgrade pip
        pip install pipenv
        make install
    - name: Testing and Coverage
      run: |
        make test
    - name: Coding Style
      run: |
        pipenv run pylint $(git ls-files '*.py')
    - name: Create Executable
      run: |
        make build-windows
